[tool.poetry]
name = "shinigami"
version = "0.0.1"
description = "WhatsApp Bot"
authors = ["MhankBarBar <mhankbarbar@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
neonize = "^0.0.4"
python-magic-bin = "^0.4.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
shinigami = "Shinigami.main:start"